"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.spacedReset = exports.reset = exports.reverse = exports.blink = exports.hidden = exports.underscore = exports.HIGHLIGHT_COLOR = exports.TEXT_COLOR = void 0;
const underscore = '\x1b[4m';
exports.underscore = underscore;
const blink = '\x1b[5m';
exports.blink = blink;
const reverse = '\x1b[7m';
exports.reverse = reverse;
const hidden = '\x1b[8m';
exports.hidden = hidden;
const reset = '\x1b[0m';
exports.reset = reset;
const spacedReset = ` ${reset} `;
exports.spacedReset = spacedReset;
var TEXT_COLOR;
(function (TEXT_COLOR) {
    TEXT_COLOR["black"] = "\u001B[30m";
    TEXT_COLOR["red"] = "\u001B[31m";
    TEXT_COLOR["green"] = "\u001B[32m";
    TEXT_COLOR["yellow"] = "\u001B[33m";
    TEXT_COLOR["blue"] = "\u001B[34m";
    TEXT_COLOR["magenta"] = "\u001B[35m";
    TEXT_COLOR["cyan"] = "\u001B[36m";
    TEXT_COLOR["white"] = "\u001B[37m";
    TEXT_COLOR["reset"] = "\u001B[0m";
    TEXT_COLOR["bright"] = "\u001B[1m";
    // dim = '\x1b[2m',
    TEXT_COLOR["dim"] = "\u001B[30m";
})(TEXT_COLOR || (TEXT_COLOR = {}));
exports.TEXT_COLOR = TEXT_COLOR;
var HIGHLIGHT_COLOR;
(function (HIGHLIGHT_COLOR) {
    HIGHLIGHT_COLOR["BGblack"] = "\u001B[40m";
    HIGHLIGHT_COLOR["BGred"] = "\u001B[41m";
    HIGHLIGHT_COLOR["BGgreen"] = "\u001B[42m";
    HIGHLIGHT_COLOR["BGyellow"] = "\u001B[43m";
    HIGHLIGHT_COLOR["BGblue"] = "\u001B[44m";
    HIGHLIGHT_COLOR["BGmagenta"] = "\u001B[45m";
    HIGHLIGHT_COLOR["BGcyan"] = "\u001B[46m";
    HIGHLIGHT_COLOR["BGwhite"] = "\u001B[47m";
})(HIGHLIGHT_COLOR || (HIGHLIGHT_COLOR = {}));
exports.HIGHLIGHT_COLOR = HIGHLIGHT_COLOR;
