"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runCLI = exports.cli = exports.addCommands = exports.addCommand = exports.logHold = exports.logBar = exports.log = exports.error = exports.warn = exports.underscore = exports.reverse = exports.spacedReset = exports.reset = exports.hidden = exports.blink = exports.TEXT_COLOR = exports.HIGHLIGHT_COLOR = exports.jesterAnim = exports.enableColoredLogs = exports.coloredLogs = exports.FORMAT = exports.CHECK = exports.initializeCLI = exports.settings = void 0;
var init_1 = require("./src/init");
Object.defineProperty(exports, "settings", { enumerable: true, get: function () { return init_1.settings; } });
Object.defineProperty(exports, "initializeCLI", { enumerable: true, get: function () { return init_1.initializeCLI; } });
var format_1 = require("./src/format");
Object.defineProperty(exports, "CHECK", { enumerable: true, get: function () { return format_1.CHECK; } });
Object.defineProperty(exports, "FORMAT", { enumerable: true, get: function () { return format_1.FORMAT; } });
Object.defineProperty(exports, "coloredLogs", { enumerable: true, get: function () { return format_1.coloredLogs; } });
Object.defineProperty(exports, "enableColoredLogs", { enumerable: true, get: function () { return format_1.enableColoredLogs; } });
var animation_1 = require("./src/animation");
Object.defineProperty(exports, "jesterAnim", { enumerable: true, get: function () { return animation_1.jesterAnim; } });
var colors_1 = require("./src/colors");
Object.defineProperty(exports, "HIGHLIGHT_COLOR", { enumerable: true, get: function () { return colors_1.HIGHLIGHT_COLOR; } });
Object.defineProperty(exports, "TEXT_COLOR", { enumerable: true, get: function () { return colors_1.TEXT_COLOR; } });
Object.defineProperty(exports, "blink", { enumerable: true, get: function () { return colors_1.blink; } });
Object.defineProperty(exports, "hidden", { enumerable: true, get: function () { return colors_1.hidden; } });
Object.defineProperty(exports, "reset", { enumerable: true, get: function () { return colors_1.reset; } });
Object.defineProperty(exports, "spacedReset", { enumerable: true, get: function () { return colors_1.spacedReset; } });
Object.defineProperty(exports, "reverse", { enumerable: true, get: function () { return colors_1.reverse; } });
Object.defineProperty(exports, "underscore", { enumerable: true, get: function () { return colors_1.underscore; } });
var log_1 = require("./src/log");
Object.defineProperty(exports, "warn", { enumerable: true, get: function () { return log_1.warn; } });
Object.defineProperty(exports, "error", { enumerable: true, get: function () { return log_1.error; } });
Object.defineProperty(exports, "log", { enumerable: true, get: function () { return log_1.log; } });
Object.defineProperty(exports, "logBar", { enumerable: true, get: function () { return log_1.logBar; } });
Object.defineProperty(exports, "logHold", { enumerable: true, get: function () { return log_1.logHold; } });
var command_1 = require("./src/command");
Object.defineProperty(exports, "addCommand", { enumerable: true, get: function () { return command_1.addCommand; } });
Object.defineProperty(exports, "addCommands", { enumerable: true, get: function () { return command_1.addCommands; } });
var cli_1 = require("./src/cli");
Object.defineProperty(exports, "cli", { enumerable: true, get: function () { return cli_1.cli; } });
Object.defineProperty(exports, "runCLI", { enumerable: true, get: function () { return cli_1.runCLI; } });
